python3: can't open file '/home/pi/bots/main.py': [Errno 2] No such file or directory
